import json
import os
import tempfile
import uuid
from datetime import datetime
from passlib.hash import bcrypt
from pydantic import BaseModel, Field, model_validator
from typing import List


type UserID = str
type Password = str
type PasswordHash = str
type UUID = str


class User(BaseModel):
    """
    User model representing a user in the system.

    Attributes:
        user_id (UserID): The unique identifier for the user.
        password_hash (PasswordHash): The hashed password for the user.
        uuid (UUID): A unique identifier for the user instance, generated by default.
        since (datetime): The timestamp indicating when the user was created, defaults to the current time.
        active (bool): A flag indicating whether the user is active, defaults to True.

    Methods:
        hash_password(cls, values):
            Validates and hashes the user's password before model creation.
            Raises:
                ValueError: If both `password` and `password_hash` are provided, or if neither is provided.

        verify_password(plain_text: Password) -> bool:
            Verifies a plain text password against the stored hashed password.

        __hash__():
            Returns a hash value for the user based on the `user_id`.

        __eq__(value):
            Compares the user instance with another value based on the `uuid`.
    """

    user_id: UserID
    password_hash: PasswordHash
    uuid: UUID = Field(default_factory=lambda: str(uuid.uuid4()))
    since: datetime = Field(default_factory=datetime.now)
    active: bool = True

    @model_validator(mode="before")
    @classmethod
    def hash_password(cls, values):
        """
        Hashes a password and ensures proper validation of input values.

        This method checks if a "password" key exists in the input dictionary `values`.
        If a "password" is provided, it hashes the password using bcrypt with 12 rounds
        and stores the resulting hash in the "password_hash" key. If both "password" and
        "password_hash" are provided, a ValueError is raised to prevent conflicts.
        Additionally, if neither "password" nor "password_hash" is provided, a ValueError
        is raised to enforce the presence of at least one.

        Args:
            values (dict): A dictionary containing user data, including "password" or
                           "password_hash".

        Returns:
            dict: The updated dictionary with the hashed password stored in the
                  "password_hash" key.

        Raises:
            ValueError: If both "password" and "password_hash" are provided, or if neither
                        is provided.
        """
        if "password" in values:
            if "password_hash" in values:
                raise ValueError("Cannot provide both password and password_hash")
            values["password_hash"] = bcrypt.using(rounds=12).hash(
                values.pop("password")
            )
        elif "password_hash" not in values:
            raise ValueError("Either password or password_hash must be provided")
        return values

    def verify_password(self, plain_text: Password) -> bool:
        """
        Verifies if the provided plain text password matches the stored password hash.

        Args:
            plain_text (Password): The plain text password to verify.

        Returns:
            bool: True if the password matches the hash, False otherwise.
        """
        return bcrypt.verify(plain_text, self.password_hash)

    def __hash__(self) -> int:
        return hash(self.user_id)

    def __eq__(self, value):
        return self.uuid == value


class Cookie(BaseModel):
    """
    A model representing a user session cookie with functionality to save, load,
    and check expiration.

    Attributes:
        last_login (datetime): The timestamp of the last login. Defaults to the current time.

    Methods:
        save(user: User) -> None:
            Saves the cookie data to a temporary file specific to the user.

        load(user: User) -> Cookie:
            Loads the cookie data from a temporary file specific to the user.
            If loading fails, returns a cookie with a last login timestamp
            set to 2 hours ago.

        expired() -> bool:
            Checks if the cookie has expired. A cookie is considered expired
            if more than 1 hour (3600 seconds) has passed since the last login.
    """

    last_login: datetime = Field(default_factory=datetime.now)

    def save(self, user: User) -> None:
        """
        Saves user information to a temporary file as a cookie.

        The method creates a temporary file in the system's temporary directory
        with the user's UUID as the filename and writes the user's ID and last
        login timestamp in ISO 8601 format to the file.

        Args:
            user (User): The user object containing the user's information.

        Raises:
            OSError: If there is an issue writing to the temporary file.
        """
        temp_dir = tempfile.gettempdir()
        cookie_path = f"{temp_dir}/{user.uuid}.cookie"
        with open(cookie_path, "w") as cookie_file:
            cookie_file.write(f"{user.user_id}.{self.last_login.isoformat()}")

    @classmethod
    def load(cls, user: User) -> "Cookie":
        """
        Load a Cookie instance for the given user.

        This method attempts to load a Cookie object from a file in the system's
        temporary directory. If the file does not exist, it creates a new Cookie
        instance with a default `last_login` time set to 2 hours ago.

        Args:
            user (User): The user for whom the Cookie is being loaded.

        Returns:
            Cookie: An instance of the Cookie class with the `last_login` time
            either loaded from the file or set to a default value.
        """
        temp_dir = tempfile.gettempdir()
        cookie_path = f"{temp_dir}/{user.uuid}.cookie"
        if not os.path.exists(cookie_path):
            return cls(last_login=datetime.now() - datetime.timedelta(hours=2))
        else:
            with open(cookie_path, "r") as f:
                data = f.read().split(".")
                return cls(last_login=datetime.fromisoformat(data[1]))

    def expired(self) -> bool:
        """
        Determines if the user's session has expired.

        Returns:
            bool: True if the time elapsed since the last login exceeds 3600 seconds (1 hour), 
            otherwise False.
        """
        return (datetime.now() - self.last_login).total_seconds() > 3600


class UserDB(BaseModel):
    users: List[User] = []

    def add_user(self, user: User) -> None:
        """
        Adds a new user to the database.

        Args:
            user (User): The user object to be added to the database.

        Raises:
            ValueError: If a user with the same user_id already exists in the database.
        """
        if any(existing_user.user_id == user.user_id for existing_user in self.users):
            raise ValueError(f"User ID '{user.user_id}' already exists")
        self.users.append(user)

    def authenticate(self, user_id: UserID, password: Password) -> bool:
        """
        Authenticates a user by checking the provided user_id and password.

        Args:
            user_id (UserID): The unique identifier for the user.
            password (Password): The plain text password to verify.

        Returns:
            bool: True if the authentication is successful, False otherwise.
        """
        for user in self.users:
            if user.user_id == user_id and user.verify_password(password):
                return True
        return False

    def save(self, filepath: str) -> None:
        def default_serializer(obj) -> str:
            if isinstance(obj, datetime):
                return obj.isoformat()
            raise TypeError(f"Type {type(obj)} not serializable")

        with open(filepath, "w") as f:
            json.dump(self.model_dump(), f, indent=2, default=default_serializer)


    @classmethod
    def load(cls, filepath: str = "user.json"):
        with open(filepath, "r") as f:
            return cls.model_validate_json(f.read())
